### ISSUE TITLE
-masm=intel doesn't work on non-x86 systems

### ISSUE THREAD

**Issue by mchelaru** [harikrishnan94/cxx-compiler-explorer#13]
https://github.com/harikrishnan94/cxx-compiler-explorer/blob/216ebc9fddaddddddbe2d24966fbf31075e2c209/src/compile_commands.ts#L50

Compilation fails on ARM based systems, not to mention that some people don't like the Intel syntax.

**Comment by harikrishnan94** [comment]
This is removed in v0.5.2. Also verified in Apple M1 Mac. Can you check if you still face the issue?
