### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by Trass3r** [harikrishnan94/cxx-compiler-explorer#2]
I tried your extension on a simple PlatformIO example project (using a compile_commands.json generated from `pio run --verbose`).
The 'Disassemble with extra args' command **is** called cause it opens the input prompt. But after that nothing happens and there is no entry in the Developer Tools Console either.

**Comment by harikrishnan94** [comment]
Yes, working on it

**Comment by harikrishnan94** [comment]
Fixed, please update the extension
