### ISSUE TITLE
Since 0.2.0, extension does not work (cannot compile [file])

### ISSUE THREAD

**Issue by Destroyerrrocket** [harikrishnan94/cxx-compiler-explorer#3]
the output from the extension is: g++: error: : No such file or directory. Feel free to ask for anything.

**Comment by dylanede** [comment]
I'm getting this as well. Maybe the working directory the g++ command is running in is wrong?

**Comment by dprogm** [comment]
@Destroyerrrocket Where do you see this output? In my case it simply doesn't do anything (no assembly view opens). On Mac OS everything works fine.

**Comment by Destroyerrrocket** [comment]
It is working currently, I have no idea why
