### ISSUE TITLE
Extension does not recognize out of tree builds over RemoteSSH

### ISSUE THREAD

**Issue by anatolyburakov** [harikrishnan94/cxx-compiler-explorer#4]
Issue Type: <b>Bug</b>

I'm trying to use this with an out-of-tree build over RemoteSSH extension. I'm getting errors about not being able to find the files in "compile_commands.json". For example:

```
file:///home/anatoly/playground/memfd_fallocate/sparsetest.c is not found in compile_commands.json
```

Presumably this happens either because the extension is either not trying to get canonical path to files in the .json files, or because it doesn't understand how to work over RemoteSSH. Either way, not working...

Extension version: 0.2.0
VS Code version: Code - Insiders 1.39.0-insider (695ee74864ef93d10f5de0861cb66af190e76211, 2019-10-02T08:56:48.092Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.15.0-65-generic

**Comment by harikrishnan94** [comment]
@anatolyburakov , v0.5.2 is out. I've tested the extension with Remote SSH, and it seems to be working as expected.
Can you check if the update solves your problem?
Feel free to re-open if you still face the same issue.
