### ISSUE TITLE
Escaped double quotes are not respected in argument splitting

### ISSUE THREAD

**Issue by dprogm** [harikrishnan94/cxx-compiler-explorer#40]
Suppose using the following compile command:
```json
[
  {
    "directory": "/Users/hero/cpp_test/build",
    "command": "/usr/bin/c++ -DSOME_VAR=\\\"\\\" -std=gnu++17 -o CMakeFiles/cpp_test.dir/main.cpp.o -c /Users/hero/cpp_test/main.cpp",
    "file": "/Users/hero/cpp_test/main.cpp"
  }
]
```
The intention is to pass the double quotes to `SOME_VAR`. The current parser implementation does not recognize this pattern which causes the actual compile command to fail because the parser yields just two arguments.

https://github.com/harikrishnan94/cxx-compiler-explorer/blob/08ecdb9b2a6e5d9cb7b61dd06b7c0aa380c230ff/src/compdb.ts#L321

Because  the last `quoteChar` is not a double quote the whole remaining string is handled as one argument.

I will prepare a PR. But maybe there is already an argument parsing library available?

**Comment by harikrishnan94** [comment]
Nothing, I'm aware of. Thanks for efforts in identifying this issue.
